# Generated by Django 5.0.4 on 2024-04-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('type', models.CharField()),
                ('body_party', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('fatigue', models.IntegerField()),
                ('duration', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hero_app.activitytype')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(blank=True, null=True)),
                ('fatigue', models.CharField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('activity', models.ManyToManyField(blank=True, null=True, to='Hero_app.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('age', models.IntegerField()),
                ('fat_percent', models.IntegerField(blank=True, null=True)),
                ('days', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hero_app.day')),
            ],
        ),
    ]
