# Generated by Django 5.0.4 on 2024-04-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='activity',
            field=models.ManyToManyField(blank=True, to='Hero_app.activity'),
        ),
    ]
