# Generated by Django 5.0.4 on 2024-04-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero_app', '0002_alter_day_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fatigue',
            field=models.CharField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='fatigue',
            field=models.CharField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='mood',
            field=models.CharField(blank=True, choices=[(1, 'Unmotivated'), (2, 'Neutral'), (3, 'Ready'), (4, 'Motivated'), (5, 'Eager')], null=True),
        ),
    ]
