# Generated by Django 5.0.4 on 2024-04-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero_app', '0003_alter_activity_fatigue_alter_day_fatigue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='char',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='char',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
