# Generated by Django 5.0.4 on 2024-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero_app', '0004_char_bmi_alter_char_height_alter_char_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
