# Generated by Django 5.0.4 on 2024-04-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero_app', '0005_alter_activitytype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fatigue',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], null=True),
        ),
    ]
