# Generated by Django 5.0.4 on 2024-04-07 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero_app', '0007_activity_date_alter_day_fatigue_alter_day_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique_for_date=True),
        ),
        migrations.CreateModel(
            name='WeightIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hero_app.char')),
            ],
        ),
    ]
