# Generated by Django 5.0.4 on 2024-04-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hero_app', '0008_alter_day_date_weightin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='activity',
            field=models.ManyToManyField(blank=True, null=True, to='Hero_app.activity'),
        ),
    ]
